# Generated by Django 5.2.1 on 2025-05-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('rent', 'For Rent')], default='rent', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('has_furniture', models.BooleanField(blank=True, null=True)),
                ('has_appliances', models.BooleanField(blank=True, null=True)),
                ('has_wifi', models.BooleanField(blank=True, null=True)),
                ('has_parking', models.BooleanField(blank=True, null=True)),
                ('transport', models.TextField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, to='belledemeure.amenity')),
            ],
        ),
    ]
