# Generated by Django 5.2.1 on 2025-05-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belledemeure', '0003_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
