# Generated by Django 5.2.1 on 2025-05-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belledemeure', '0005_alter_property_price_alter_property_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='belledemeure.amenity'),
        ),
    ]
